package gae.piaz.performance.controller;

import gae.piaz.performance.controller.dto.BookDTO;
import gae.piaz.performance.model.Book;
import gae.piaz.performance.service.BookService;
import gae.piaz.performance.service.mapper.BookMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.stream.Collectors;

/**
 * Generated by Springboot-3layer-Generator at Jan 6, 2021, 8:30:41 PM
 */
@RestController
@RequestMapping("/books/")
public class BookControllerDTO {

    @Autowired
    private BookService service;

    @Autowired
    private BookMapper mapper;

    @GetMapping
    public ResponseEntity<List<BookDTO>> readAll() {
        List<Book> entity = service.readAll();
        return ResponseEntity.ok(entity.stream().map(b -> mapper.toDto(b)).collect(Collectors.toList()));
    }

    @PostMapping
    public ResponseEntity<BookDTO> create(@RequestBody BookDTO dto) {
        Book entity = mapper.toEntity(dto);
        entity = service.create(entity);
        return ResponseEntity.ok(mapper.toDto(entity));
    }

    @GetMapping("{isbn}")
    public ResponseEntity<List<BookDTO>> readOne(@PathVariable("isbn") String isbn) {
        List<Book> entity = service.readOne(isbn);
        return ResponseEntity.ok(entity.stream().map(b -> mapper.toDto(b)).collect(Collectors.toList()));
    }


}