package gae.piaz.performance.controller;

import gae.piaz.performance.model.User;
import gae.piaz.performance.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/**
* Generated by Springboot-3layer-Generator at Jan 6, 2021, 8:30:41 PM
*/
@RestController
@RequestMapping("/user/")
public class UserController implements CrudController<User, Integer>{

    @Autowired
    private UserService service;

    @Override
    public ResponseEntity<User> create(@RequestBody User entity) {
        return ResponseEntity.ok(service.create(entity));
    }

    @Override
    public ResponseEntity<User> update(@RequestBody User entity) {
        return ResponseEntity.ok(service.update(entity));
    }

    @Override
    public ResponseEntity<Page<User>> read(
            @RequestBody User entity,
            @RequestParam("page") Integer page,
            @RequestParam("size") Integer size) {
        Pageable pageable = PageRequest.of(page,size);
        return ResponseEntity.ok(service.read(entity,pageable));
    }

    @Override
    public ResponseEntity<User> readOne(@PathVariable("id") Integer primaryKey) {
        return ResponseEntity.ok(service.readOne(primaryKey));
    }

    @Override
    public void delete(Integer primaryKey) {
        service.delete(primaryKey);
    }
}