package gae.piaz.performance.controller.dto;

import lombok.Data;

import javax.validation.constraints.Size;

/**
 * Generated by Springboot-3layer-Generator at Jan 6, 2021, 8:30:41 PM
 */
@Data
public class BookDTO {

    private Integer bookId;

    @Size(min = 5)
    private String author;

    @Size(min = 10)
    private String isbn;

    @Size(min = 5)
    private String title;

    private Integer year;

}
