package gae.piaz.performance.controller.dto;

import lombok.Data;

/**
* Generated by Springboot-3layer-Generator at Jan 6, 2021, 8:30:41 PM
*/
@Data
public class BookDTO {

    private long serialVersionUID;
    private Integer bookId;
    private String author;
    private String isbn;
    private String title;
    private Integer year;
    private java.util.List orders;

}
