package gae.piaz.performance.controller.dto;

import lombok.Data;

/**
* Generated by Springboot-3layer-Generator at Jan 6, 2021, 8:30:41 PM
*/
@Data
public class OrderDTO {

    private long serialVersionUID;
    private Integer orderId;
    private Integer quantity;
    private gae.piaz.performance.model.Book book;
    private gae.piaz.performance.model.User user;

}
