package gae.piaz.performance.controller.dto;

import lombok.Data;

/**
* Generated by Springboot-3layer-Generator at Jan 6, 2021, 8:30:41 PM
*/
@Data
public class UserDTO {

    private long serialVersionUID;
    private Integer userId;
    private String firstName;
    private String lastName;
    private java.util.List orders;

}
