package gae.piaz.performance.service.mapper;

import gae.piaz.performance.controller.dto.BookDTO;
import gae.piaz.performance.model.Book;
import org.mapstruct.Mapper;

/**
* Generated by Springboot-3layer-Generator at Jan 6, 2021, 8:30:41 PM
*/
@Mapper(componentModel = "spring")
public interface BookMapper {

    Book toEntity(BookDTO dto);

    BookDTO toDto(Book entity);

}