package gae.piaz.performance.service.mapper;

import gae.piaz.performance.controller.dto.OrderDTO;
import gae.piaz.performance.model.Order;
import org.mapstruct.Mapper;

/**
* Generated by Springboot-3layer-Generator at Jan 6, 2021, 8:30:41 PM
*/
@Mapper(componentModel = "spring")
public interface OrderMapper {

    Order toEntity(OrderDTO dto);

    OrderDTO toDto(Order entity);

}