package gae.piaz.performance.service.mapper;

import gae.piaz.performance.controller.dto.UserDTO;
import gae.piaz.performance.model.User;
import org.mapstruct.Mapper;

/**
* Generated by Springboot-3layer-Generator at Jan 6, 2021, 8:30:41 PM
*/
@Mapper(componentModel = "spring")
public interface UserMapper {

    User toEntity(UserDTO dto);

    UserDTO toDto(User entity);

}