package gae.piaz.performance.repository;

import gae.piaz.performance.model.Order;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Springboot-3layer-Generator at Jan 6, 2021, 8:30:41 PM
*/
@Repository
public interface OrderRepository extends JpaRepository<Order, Integer> {

}