version: '3.1'

services:

  db-service:
    container_name: db-service
    build:
      context: ../db
    restart: always
    env_file:
      - ../db/.env
    ports:
      - "5000:5432"
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 250M
        reservations:
          memory: 250M
    
  nginx:
    image: nginx:latest
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - spring-boot
      - node-js
    ports:
      - "4000:4000"
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: 1
          memory: 250M
        reservations:
          memory: 250M
          
  #############################
  
  spring-boot:
    build: 
        context: ../spring-boot-performance
    depends_on: 
      - db-service
    expose:
      - "8080"
    restart: always
    
          
  node-js:
    build: 
        context: ../nodejs-performance
    depends_on: 
      - db-service
    expose:
      - "8080"
    restart: always
    
