version: '3.1'

services:

  db-service:
    container_name: db-service
    build:
      context: ../db
    restart: always
    env_file:
      - ../db/.env
    ports:
      - "5000:5432"
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 100M
    
  microservice:
    build: 
        context: ../spring-boot-performance # ../nodejs-performance
    depends_on: 
      - "db-service"
    expose:
      - "8080"
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
      
  nginx:
    image: nginx:latest
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "microservice"
    ports:
      - "4000:4000"
