package gae.piaz.performance.service;

import gae.piaz.performance.model.Book;

import java.util.List;

/**
 * Generated by Springboot-3layer-Generator at Jan 6, 2021, 8:30:41 PM
 */
public interface BookService extends CrudService<Book, Integer> {

    List<Book> readAll();

    List<Book> readOne(String isbn);
}